pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'realm-of-the-guard'

def rallyProjectDirectory = file('../rally-of-the-guard')
if (new File(rallyProjectDirectory, 'settings.gradle').isFile()) {
	includeBuild(rallyProjectDirectory)
}
